name: Lint code using golangci-lint

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  lint:
    # Name the Job
    name: Lint code
    # Set the type of machine to run on
    runs-on: ubuntu-20.04

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Allow unsecure commands
        run: |
            echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v1.2.1
